// flow-typed signature: d76bd70ac96e51af28cef41b17caf9ed
// flow-typed version: <<STUB>>/@paypal/applepay-components_v1.7.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/applepay-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/applepay-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/applepay-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src/__tests__/applepay.test' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src/__tests__/util.test' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src/applepay' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src/babel.config' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src/constants' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src/logging' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src/types' {
  declare module.exports: any;
}

declare module '@paypal/applepay-components/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/applepay-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/__sdk__'>;
}
declare module '@paypal/applepay-components/src/__tests__/applepay.test.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src/__tests__/applepay.test'>;
}
declare module '@paypal/applepay-components/src/__tests__/util.test.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src/__tests__/util.test'>;
}
declare module '@paypal/applepay-components/src/applepay.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src/applepay'>;
}
declare module '@paypal/applepay-components/src/babel.config.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src/babel.config'>;
}
declare module '@paypal/applepay-components/src/constants.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src/constants'>;
}
declare module '@paypal/applepay-components/src/index' {
  declare module.exports: $Exports<'@paypal/applepay-components/src'>;
}
declare module '@paypal/applepay-components/src/index.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src'>;
}
declare module '@paypal/applepay-components/src/logging.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src/logging'>;
}
declare module '@paypal/applepay-components/src/types.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src/types'>;
}
declare module '@paypal/applepay-components/src/util.js' {
  declare module.exports: $Exports<'@paypal/applepay-components/src/util'>;
}
