// flow-typed signature: ea820b0e76afa1c0b4d194ddfd8160c1
// flow-typed version: <<STUB>>/@paypal/card-components_v1.0.56/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/card-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/card-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/card-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/card-components/globals' {
  declare module.exports: any;
}

declare module '@paypal/card-components/src/component' {
  declare module.exports: any;
}

declare module '@paypal/card-components/src/contingency-flow' {
  declare module.exports: any;
}

declare module '@paypal/card-components/src/declarations' {
  declare module.exports: any;
}

declare module '@paypal/card-components/src' {
  declare module.exports: any;
}

declare module '@paypal/card-components/src/types' {
  declare module.exports: any;
}

declare module '@paypal/card-components/src/zoid/contingency-flow/component' {
  declare module.exports: any;
}

declare module '@paypal/card-components/src/zoid/contingency-flow' {
  declare module.exports: any;
}

declare module '@paypal/card-components/src/zoid/contingency-flow/props' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/american-express/american-express' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/american-express/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/american-express' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/apple-pay/apple-pay' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/apple-pay/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/apple-pay' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/browser-detection' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/client' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/get-configuration' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/ajax-driver' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/default-request' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/get-user-agent' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/adapters/credit-card-tokenization' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/adapters/error' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/generators/credit-card-tokenization' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/request' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/is-http' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/jsonp-driver' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/parse-body' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/prep-body' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/client/request/xhr' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/data-collector/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/data-collector/fraudnet' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/data-collector' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/data-collector/kount' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/data-collector/vendor/sjcl' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/google-payment/browser-detection' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/google-payment/google-payment' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/google-payment' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/external/attribute-validation-error' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/external/compose-url' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/external/hosted-fields' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/external/inject-frame' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/shared/browser-detection' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/shared/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/shared/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/shared/find-parent-tags' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/ideal/external/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/ideal/external/ideal' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/ideal' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/ideal/shared/browser-detection' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/ideal/shared/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/ideal/shared/events' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/ideal/static/sandbox-approval' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/add-metadata' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/analytics' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/apply-iframe-src' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/assign' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/basic-component-verification' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/batch-execute-functions' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/braintree-error' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/bus/check-origin' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/bus/events' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/bus' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/camel-case-to-snake-case' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/classlist' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/convert-methods-to-error' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/convert-to-braintree-error' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/create-authorization-data' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/create-restricted-input' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/deferred' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/destructor' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/enumerate' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/event-emitter' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/fake-restricted-input' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/frame-service' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/modal' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup-bridge' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup/compose-options' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup/position' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/browser-detection' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/events' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/generate-google-pay-configuration' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/get-hosted-fields-cardform' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/is-https' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/is-whitelisted-domain' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/json-clone' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/methods' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/once' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/promise' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/querystring' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/redirect' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/sanitize-html' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/throw-if-no-callback' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/use-min' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/vendor/polyfill' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/lib/vendor/uuid' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/masterpass/external/masterpass' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/masterpass' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/masterpass/shared/browser-detection' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/masterpass/shared/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/masterpass/shared/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/payment-request/external/payment-request' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/payment-request' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/payment-request/shared/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/paypal-checkout/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/paypal-checkout' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/paypal-checkout/paypal-checkout' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/paypal/external/paypal' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/paypal' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/paypal/shared/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/paypal/shared/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/external/three-d-secure' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/three-d-secure' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/shared/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/shared/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/shared/events' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/unionpay' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/unionpay/shared/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/unionpay/shared/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/unionpay/shared/unionpay' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/us-bank-account/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/us-bank-account/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/us-bank-account' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/us-bank-account/us-bank-account' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/vault-manager' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/vault-manager/vault-manager' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/venmo' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/venmo/shared/browser-detection' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/venmo/shared/constants' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/venmo/shared/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/venmo/shared/supports-venmo' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/venmo/venmo' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/visa-checkout/errors' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/visa-checkout' {
  declare module.exports: any;
}

declare module '@paypal/card-components/vendor/braintree-web/visa-checkout/visa-checkout' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/card-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/card-components/__sdk__'>;
}
declare module '@paypal/card-components/globals.js' {
  declare module.exports: $Exports<'@paypal/card-components/globals'>;
}
declare module '@paypal/card-components/src/component.js' {
  declare module.exports: $Exports<'@paypal/card-components/src/component'>;
}
declare module '@paypal/card-components/src/contingency-flow.js' {
  declare module.exports: $Exports<'@paypal/card-components/src/contingency-flow'>;
}
declare module '@paypal/card-components/src/declarations.js' {
  declare module.exports: $Exports<'@paypal/card-components/src/declarations'>;
}
declare module '@paypal/card-components/src/index' {
  declare module.exports: $Exports<'@paypal/card-components/src'>;
}
declare module '@paypal/card-components/src/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/src'>;
}
declare module '@paypal/card-components/src/types.js' {
  declare module.exports: $Exports<'@paypal/card-components/src/types'>;
}
declare module '@paypal/card-components/src/zoid/contingency-flow/component.js' {
  declare module.exports: $Exports<'@paypal/card-components/src/zoid/contingency-flow/component'>;
}
declare module '@paypal/card-components/src/zoid/contingency-flow/index' {
  declare module.exports: $Exports<'@paypal/card-components/src/zoid/contingency-flow'>;
}
declare module '@paypal/card-components/src/zoid/contingency-flow/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/src/zoid/contingency-flow'>;
}
declare module '@paypal/card-components/src/zoid/contingency-flow/props.js' {
  declare module.exports: $Exports<'@paypal/card-components/src/zoid/contingency-flow/props'>;
}
declare module '@paypal/card-components/vendor/braintree-web/american-express/american-express.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/american-express/american-express'>;
}
declare module '@paypal/card-components/vendor/braintree-web/american-express/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/american-express/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/american-express/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/american-express'>;
}
declare module '@paypal/card-components/vendor/braintree-web/american-express/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/american-express'>;
}
declare module '@paypal/card-components/vendor/braintree-web/apple-pay/apple-pay.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/apple-pay/apple-pay'>;
}
declare module '@paypal/card-components/vendor/braintree-web/apple-pay/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/apple-pay/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/apple-pay/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/apple-pay'>;
}
declare module '@paypal/card-components/vendor/braintree-web/apple-pay/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/apple-pay'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/browser-detection.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/browser-detection'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/client.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/client'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/get-configuration.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/get-configuration'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/ajax-driver.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/ajax-driver'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/default-request.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/default-request'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/get-user-agent.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/get-user-agent'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/adapters/credit-card-tokenization.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/graphql/adapters/credit-card-tokenization'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/adapters/error.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/graphql/adapters/error'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/generators/credit-card-tokenization.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/graphql/generators/credit-card-tokenization'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/graphql'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/graphql'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/graphql/request.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/graphql/request'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/is-http.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/is-http'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/jsonp-driver.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/jsonp-driver'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/parse-body.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/parse-body'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/prep-body.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/prep-body'>;
}
declare module '@paypal/card-components/vendor/braintree-web/client/request/xhr.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/client/request/xhr'>;
}
declare module '@paypal/card-components/vendor/braintree-web/data-collector/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/data-collector/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/data-collector/fraudnet.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/data-collector/fraudnet'>;
}
declare module '@paypal/card-components/vendor/braintree-web/data-collector/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/data-collector'>;
}
declare module '@paypal/card-components/vendor/braintree-web/data-collector/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/data-collector'>;
}
declare module '@paypal/card-components/vendor/braintree-web/data-collector/kount.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/data-collector/kount'>;
}
declare module '@paypal/card-components/vendor/braintree-web/data-collector/vendor/sjcl.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/data-collector/vendor/sjcl'>;
}
declare module '@paypal/card-components/vendor/braintree-web/google-payment/browser-detection.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/google-payment/browser-detection'>;
}
declare module '@paypal/card-components/vendor/braintree-web/google-payment/google-payment.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/google-payment/google-payment'>;
}
declare module '@paypal/card-components/vendor/braintree-web/google-payment/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/google-payment'>;
}
declare module '@paypal/card-components/vendor/braintree-web/google-payment/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/google-payment'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/external/attribute-validation-error.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields/external/attribute-validation-error'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/external/compose-url.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields/external/compose-url'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/external/hosted-fields.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields/external/hosted-fields'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/external/inject-frame.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields/external/inject-frame'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/shared/browser-detection.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields/shared/browser-detection'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/shared/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields/shared/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/shared/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields/shared/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/hosted-fields/shared/find-parent-tags.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/hosted-fields/shared/find-parent-tags'>;
}
declare module '@paypal/card-components/vendor/braintree-web/ideal/external/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/ideal/external/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/ideal/external/ideal.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/ideal/external/ideal'>;
}
declare module '@paypal/card-components/vendor/braintree-web/ideal/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/ideal'>;
}
declare module '@paypal/card-components/vendor/braintree-web/ideal/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/ideal'>;
}
declare module '@paypal/card-components/vendor/braintree-web/ideal/shared/browser-detection.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/ideal/shared/browser-detection'>;
}
declare module '@paypal/card-components/vendor/braintree-web/ideal/shared/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/ideal/shared/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/ideal/shared/events.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/ideal/shared/events'>;
}
declare module '@paypal/card-components/vendor/braintree-web/ideal/static/sandbox-approval.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/ideal/static/sandbox-approval'>;
}
declare module '@paypal/card-components/vendor/braintree-web/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web'>;
}
declare module '@paypal/card-components/vendor/braintree-web/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/add-metadata.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/add-metadata'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/analytics.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/analytics'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/apply-iframe-src.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/apply-iframe-src'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/assign.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/assign'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/basic-component-verification.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/basic-component-verification'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/batch-execute-functions.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/batch-execute-functions'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/braintree-error.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/braintree-error'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/bus/check-origin.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/bus/check-origin'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/bus/events.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/bus/events'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/bus/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/bus'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/bus/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/bus'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/camel-case-to-snake-case.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/camel-case-to-snake-case'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/classlist.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/classlist'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/convert-methods-to-error.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/convert-methods-to-error'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/convert-to-braintree-error.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/convert-to-braintree-error'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/create-authorization-data.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/create-authorization-data'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/create-restricted-input.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/create-restricted-input'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/deferred.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/deferred'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/destructor.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/destructor'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/enumerate.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/enumerate'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/event-emitter.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/event-emitter'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/fake-restricted-input.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/fake-restricted-input'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/frame-service.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external/frame-service'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/modal.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/modal'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup-bridge.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup-bridge'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup/compose-options.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup/compose-options'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup/position.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/external/strategies/popup/position'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/browser-detection.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/browser-detection'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/events.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/frame-service/shared/events'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/generate-google-pay-configuration.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/generate-google-pay-configuration'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/get-hosted-fields-cardform.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/get-hosted-fields-cardform'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/is-https.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/is-https'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/is-whitelisted-domain.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/is-whitelisted-domain'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/json-clone.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/json-clone'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/methods.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/methods'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/once.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/once'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/promise.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/promise'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/querystring.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/querystring'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/redirect.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/redirect'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/sanitize-html.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/sanitize-html'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/throw-if-no-callback.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/throw-if-no-callback'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/use-min.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/use-min'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/vendor/polyfill.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/vendor/polyfill'>;
}
declare module '@paypal/card-components/vendor/braintree-web/lib/vendor/uuid.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/lib/vendor/uuid'>;
}
declare module '@paypal/card-components/vendor/braintree-web/masterpass/external/masterpass.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/masterpass/external/masterpass'>;
}
declare module '@paypal/card-components/vendor/braintree-web/masterpass/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/masterpass'>;
}
declare module '@paypal/card-components/vendor/braintree-web/masterpass/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/masterpass'>;
}
declare module '@paypal/card-components/vendor/braintree-web/masterpass/shared/browser-detection.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/masterpass/shared/browser-detection'>;
}
declare module '@paypal/card-components/vendor/braintree-web/masterpass/shared/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/masterpass/shared/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/masterpass/shared/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/masterpass/shared/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/payment-request/external/payment-request.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/payment-request/external/payment-request'>;
}
declare module '@paypal/card-components/vendor/braintree-web/payment-request/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/payment-request'>;
}
declare module '@paypal/card-components/vendor/braintree-web/payment-request/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/payment-request'>;
}
declare module '@paypal/card-components/vendor/braintree-web/payment-request/shared/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/payment-request/shared/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal-checkout/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal-checkout/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal-checkout/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal-checkout'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal-checkout/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal-checkout'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal-checkout/paypal-checkout.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal-checkout/paypal-checkout'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal/external/paypal.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal/external/paypal'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal/shared/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal/shared/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/paypal/shared/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/paypal/shared/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/external/three-d-secure.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/three-d-secure/external/three-d-secure'>;
}
declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/three-d-secure'>;
}
declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/three-d-secure'>;
}
declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/shared/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/three-d-secure/shared/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/shared/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/three-d-secure/shared/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/three-d-secure/shared/events.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/three-d-secure/shared/events'>;
}
declare module '@paypal/card-components/vendor/braintree-web/unionpay/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/unionpay'>;
}
declare module '@paypal/card-components/vendor/braintree-web/unionpay/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/unionpay'>;
}
declare module '@paypal/card-components/vendor/braintree-web/unionpay/shared/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/unionpay/shared/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/unionpay/shared/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/unionpay/shared/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/unionpay/shared/unionpay.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/unionpay/shared/unionpay'>;
}
declare module '@paypal/card-components/vendor/braintree-web/us-bank-account/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/us-bank-account/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/us-bank-account/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/us-bank-account/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/us-bank-account/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/us-bank-account'>;
}
declare module '@paypal/card-components/vendor/braintree-web/us-bank-account/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/us-bank-account'>;
}
declare module '@paypal/card-components/vendor/braintree-web/us-bank-account/us-bank-account.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/us-bank-account/us-bank-account'>;
}
declare module '@paypal/card-components/vendor/braintree-web/vault-manager/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/vault-manager'>;
}
declare module '@paypal/card-components/vendor/braintree-web/vault-manager/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/vault-manager'>;
}
declare module '@paypal/card-components/vendor/braintree-web/vault-manager/vault-manager.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/vault-manager/vault-manager'>;
}
declare module '@paypal/card-components/vendor/braintree-web/venmo/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/venmo'>;
}
declare module '@paypal/card-components/vendor/braintree-web/venmo/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/venmo'>;
}
declare module '@paypal/card-components/vendor/braintree-web/venmo/shared/browser-detection.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/venmo/shared/browser-detection'>;
}
declare module '@paypal/card-components/vendor/braintree-web/venmo/shared/constants.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/venmo/shared/constants'>;
}
declare module '@paypal/card-components/vendor/braintree-web/venmo/shared/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/venmo/shared/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/venmo/shared/supports-venmo.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/venmo/shared/supports-venmo'>;
}
declare module '@paypal/card-components/vendor/braintree-web/venmo/venmo.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/venmo/venmo'>;
}
declare module '@paypal/card-components/vendor/braintree-web/visa-checkout/errors.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/visa-checkout/errors'>;
}
declare module '@paypal/card-components/vendor/braintree-web/visa-checkout/index' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/visa-checkout'>;
}
declare module '@paypal/card-components/vendor/braintree-web/visa-checkout/index.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/visa-checkout'>;
}
declare module '@paypal/card-components/vendor/braintree-web/visa-checkout/visa-checkout.js' {
  declare module.exports: $Exports<'@paypal/card-components/vendor/braintree-web/visa-checkout/visa-checkout'>;
}
