// flow-typed signature: 1f6ec8b7f66ce07ed40fba690bd60868
// flow-typed version: <<STUB>>/@paypal/checkout-components_v5.0.312/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/checkout-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/checkout-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/checkout-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/dist/button' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/dist/test/button' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/globals' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/connect/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/connect/component.test' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/connect/interface' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/constants/api' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/constants/button' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/constants/class' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/constants' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/constants/misc' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/declarations' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/applepay/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/applepay' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/applepay/template' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/bancontact/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/bancontact' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/blik/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/blik' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/boleto/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/boleto' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/amex/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/amex' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/config.test' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/discover/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/discover' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/elo/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/elo' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/hiper/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/hiper' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/jcb/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/jcb' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/mastercard/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/mastercard' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/visa/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/card/visa' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/common' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/content' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/credit/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/credit' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/eps/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/eps' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/funding' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/funding.test' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/giropay/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/giropay' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/ideal/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/ideal' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/itau/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/itau' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/mercadopago/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/mercadopago' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/multibanco/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/multibanco' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/mybank/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/mybank' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/oxxo/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/oxxo' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/p24/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/p24' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/paidy/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/paidy' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/paylater/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/paylater' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/paypal/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/paypal' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/paypal/template' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/payu/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/payu' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/satispay/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/satispay' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/sepa/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/sepa' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/sofort/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/sofort' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/trustly/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/trustly' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/venmo/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/venmo' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/venmo/template' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/wechatpay/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/funding/wechatpay' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/hosted-buttons' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/hosted-buttons/index.test' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/hosted-buttons/types' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/hosted-buttons/utils' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/hosted-buttons/utils.test' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/interface/button' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/interface/card-fields' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/interface/fields' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/interface/hosted-buttons' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/interface/marks' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/interface/payment-fields' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/interface/wallet' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/lib/api' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/lib/errors' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/lib' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/lib/isRTLLanguage' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/lib/perceived-latency-instrumentation' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/lib/security' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/lib/session' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/marks/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/marks' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/marks/template' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/shopper-insights/interface' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/shopper-insights/shopperSession' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/shopper-insights/shopperSession.test' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/types' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/button' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/buttons' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/content' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/menu-button' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/menu-button/menu-button' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/message' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/poweredBy' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/props' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/script' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/spinner' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/style' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/styles/base' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/styles/button' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/styles/color' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/styles' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/styles/labels' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/styles/page' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/styles/responsive' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/tagline' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/buttons/util' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/chevron' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/loading' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/text' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/text/text' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/ui/tracking' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/buttons/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/buttons/container' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/buttons' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/buttons/prerender' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/buttons/util' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/card-fields/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/card-fields' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/card-fields/prerender' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/card-form/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/card-form' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/checkout/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/checkout/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/checkout/hacks' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/checkout' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/checkout/props' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/content' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/installments/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/installments' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/installments/props' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/menu/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/menu' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/menu/props' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/modal/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/modal' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/modal/props' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/payment-fields/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/payment-fields/container' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/payment-fields' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/payment-fields/prerender' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/payment-fields/props' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/qr-code/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/qr-code/container' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/qr-code' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/qr-code/prerender' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/qr-code/types' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/venmo/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/venmo/config' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/venmo' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/wallet/component' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/wallet/container' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/wallet' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/wallet/prerender' {
  declare module.exports: any;
}

declare module '@paypal/checkout-components/src/zoid/wallet/props' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/checkout-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/__sdk__'>;
}
declare module '@paypal/checkout-components/dist/button.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/dist/button'>;
}
declare module '@paypal/checkout-components/dist/test/button.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/dist/test/button'>;
}
declare module '@paypal/checkout-components/globals.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/globals'>;
}
declare module '@paypal/checkout-components/src/connect/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/connect/component'>;
}
declare module '@paypal/checkout-components/src/connect/component.test.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/connect/component.test'>;
}
declare module '@paypal/checkout-components/src/connect/interface.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/connect/interface'>;
}
declare module '@paypal/checkout-components/src/constants/api.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/constants/api'>;
}
declare module '@paypal/checkout-components/src/constants/button.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/constants/button'>;
}
declare module '@paypal/checkout-components/src/constants/class.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/constants/class'>;
}
declare module '@paypal/checkout-components/src/constants/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/constants'>;
}
declare module '@paypal/checkout-components/src/constants/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/constants'>;
}
declare module '@paypal/checkout-components/src/constants/misc.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/constants/misc'>;
}
declare module '@paypal/checkout-components/src/declarations.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/declarations'>;
}
declare module '@paypal/checkout-components/src/funding/applepay/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/applepay/config'>;
}
declare module '@paypal/checkout-components/src/funding/applepay/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/applepay'>;
}
declare module '@paypal/checkout-components/src/funding/applepay/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/applepay'>;
}
declare module '@paypal/checkout-components/src/funding/applepay/template.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/applepay/template'>;
}
declare module '@paypal/checkout-components/src/funding/bancontact/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/bancontact/config'>;
}
declare module '@paypal/checkout-components/src/funding/bancontact/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/bancontact'>;
}
declare module '@paypal/checkout-components/src/funding/bancontact/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/bancontact'>;
}
declare module '@paypal/checkout-components/src/funding/blik/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/blik/config'>;
}
declare module '@paypal/checkout-components/src/funding/blik/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/blik'>;
}
declare module '@paypal/checkout-components/src/funding/blik/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/blik'>;
}
declare module '@paypal/checkout-components/src/funding/boleto/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/boleto/config'>;
}
declare module '@paypal/checkout-components/src/funding/boleto/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/boleto'>;
}
declare module '@paypal/checkout-components/src/funding/boleto/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/boleto'>;
}
declare module '@paypal/checkout-components/src/funding/card/amex/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/amex/config'>;
}
declare module '@paypal/checkout-components/src/funding/card/amex/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/amex'>;
}
declare module '@paypal/checkout-components/src/funding/card/amex/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/amex'>;
}
declare module '@paypal/checkout-components/src/funding/card/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/config'>;
}
declare module '@paypal/checkout-components/src/funding/card/config.test.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/config.test'>;
}
declare module '@paypal/checkout-components/src/funding/card/discover/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/discover/config'>;
}
declare module '@paypal/checkout-components/src/funding/card/discover/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/discover'>;
}
declare module '@paypal/checkout-components/src/funding/card/discover/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/discover'>;
}
declare module '@paypal/checkout-components/src/funding/card/elo/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/elo/config'>;
}
declare module '@paypal/checkout-components/src/funding/card/elo/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/elo'>;
}
declare module '@paypal/checkout-components/src/funding/card/elo/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/elo'>;
}
declare module '@paypal/checkout-components/src/funding/card/hiper/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/hiper/config'>;
}
declare module '@paypal/checkout-components/src/funding/card/hiper/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/hiper'>;
}
declare module '@paypal/checkout-components/src/funding/card/hiper/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/hiper'>;
}
declare module '@paypal/checkout-components/src/funding/card/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card'>;
}
declare module '@paypal/checkout-components/src/funding/card/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card'>;
}
declare module '@paypal/checkout-components/src/funding/card/jcb/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/jcb/config'>;
}
declare module '@paypal/checkout-components/src/funding/card/jcb/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/jcb'>;
}
declare module '@paypal/checkout-components/src/funding/card/jcb/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/jcb'>;
}
declare module '@paypal/checkout-components/src/funding/card/mastercard/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/mastercard/config'>;
}
declare module '@paypal/checkout-components/src/funding/card/mastercard/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/mastercard'>;
}
declare module '@paypal/checkout-components/src/funding/card/mastercard/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/mastercard'>;
}
declare module '@paypal/checkout-components/src/funding/card/visa/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/visa/config'>;
}
declare module '@paypal/checkout-components/src/funding/card/visa/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/visa'>;
}
declare module '@paypal/checkout-components/src/funding/card/visa/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/card/visa'>;
}
declare module '@paypal/checkout-components/src/funding/common.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/common'>;
}
declare module '@paypal/checkout-components/src/funding/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/config'>;
}
declare module '@paypal/checkout-components/src/funding/content.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/content'>;
}
declare module '@paypal/checkout-components/src/funding/credit/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/credit/config'>;
}
declare module '@paypal/checkout-components/src/funding/credit/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/credit'>;
}
declare module '@paypal/checkout-components/src/funding/credit/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/credit'>;
}
declare module '@paypal/checkout-components/src/funding/eps/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/eps/config'>;
}
declare module '@paypal/checkout-components/src/funding/eps/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/eps'>;
}
declare module '@paypal/checkout-components/src/funding/eps/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/eps'>;
}
declare module '@paypal/checkout-components/src/funding/funding.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/funding'>;
}
declare module '@paypal/checkout-components/src/funding/funding.test.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/funding.test'>;
}
declare module '@paypal/checkout-components/src/funding/giropay/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/giropay/config'>;
}
declare module '@paypal/checkout-components/src/funding/giropay/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/giropay'>;
}
declare module '@paypal/checkout-components/src/funding/giropay/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/giropay'>;
}
declare module '@paypal/checkout-components/src/funding/ideal/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/ideal/config'>;
}
declare module '@paypal/checkout-components/src/funding/ideal/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/ideal'>;
}
declare module '@paypal/checkout-components/src/funding/ideal/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/ideal'>;
}
declare module '@paypal/checkout-components/src/funding/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding'>;
}
declare module '@paypal/checkout-components/src/funding/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding'>;
}
declare module '@paypal/checkout-components/src/funding/itau/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/itau/config'>;
}
declare module '@paypal/checkout-components/src/funding/itau/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/itau'>;
}
declare module '@paypal/checkout-components/src/funding/itau/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/itau'>;
}
declare module '@paypal/checkout-components/src/funding/mercadopago/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/mercadopago/config'>;
}
declare module '@paypal/checkout-components/src/funding/mercadopago/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/mercadopago'>;
}
declare module '@paypal/checkout-components/src/funding/mercadopago/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/mercadopago'>;
}
declare module '@paypal/checkout-components/src/funding/multibanco/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/multibanco/config'>;
}
declare module '@paypal/checkout-components/src/funding/multibanco/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/multibanco'>;
}
declare module '@paypal/checkout-components/src/funding/multibanco/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/multibanco'>;
}
declare module '@paypal/checkout-components/src/funding/mybank/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/mybank/config'>;
}
declare module '@paypal/checkout-components/src/funding/mybank/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/mybank'>;
}
declare module '@paypal/checkout-components/src/funding/mybank/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/mybank'>;
}
declare module '@paypal/checkout-components/src/funding/oxxo/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/oxxo/config'>;
}
declare module '@paypal/checkout-components/src/funding/oxxo/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/oxxo'>;
}
declare module '@paypal/checkout-components/src/funding/oxxo/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/oxxo'>;
}
declare module '@paypal/checkout-components/src/funding/p24/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/p24/config'>;
}
declare module '@paypal/checkout-components/src/funding/p24/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/p24'>;
}
declare module '@paypal/checkout-components/src/funding/p24/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/p24'>;
}
declare module '@paypal/checkout-components/src/funding/paidy/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paidy/config'>;
}
declare module '@paypal/checkout-components/src/funding/paidy/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paidy'>;
}
declare module '@paypal/checkout-components/src/funding/paidy/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paidy'>;
}
declare module '@paypal/checkout-components/src/funding/paylater/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paylater/config'>;
}
declare module '@paypal/checkout-components/src/funding/paylater/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paylater'>;
}
declare module '@paypal/checkout-components/src/funding/paylater/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paylater'>;
}
declare module '@paypal/checkout-components/src/funding/paypal/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paypal/config'>;
}
declare module '@paypal/checkout-components/src/funding/paypal/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paypal'>;
}
declare module '@paypal/checkout-components/src/funding/paypal/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paypal'>;
}
declare module '@paypal/checkout-components/src/funding/paypal/template.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/paypal/template'>;
}
declare module '@paypal/checkout-components/src/funding/payu/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/payu/config'>;
}
declare module '@paypal/checkout-components/src/funding/payu/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/payu'>;
}
declare module '@paypal/checkout-components/src/funding/payu/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/payu'>;
}
declare module '@paypal/checkout-components/src/funding/satispay/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/satispay/config'>;
}
declare module '@paypal/checkout-components/src/funding/satispay/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/satispay'>;
}
declare module '@paypal/checkout-components/src/funding/satispay/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/satispay'>;
}
declare module '@paypal/checkout-components/src/funding/sepa/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/sepa/config'>;
}
declare module '@paypal/checkout-components/src/funding/sepa/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/sepa'>;
}
declare module '@paypal/checkout-components/src/funding/sepa/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/sepa'>;
}
declare module '@paypal/checkout-components/src/funding/sofort/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/sofort/config'>;
}
declare module '@paypal/checkout-components/src/funding/sofort/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/sofort'>;
}
declare module '@paypal/checkout-components/src/funding/sofort/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/sofort'>;
}
declare module '@paypal/checkout-components/src/funding/trustly/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/trustly/config'>;
}
declare module '@paypal/checkout-components/src/funding/trustly/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/trustly'>;
}
declare module '@paypal/checkout-components/src/funding/trustly/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/trustly'>;
}
declare module '@paypal/checkout-components/src/funding/venmo/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/venmo/config'>;
}
declare module '@paypal/checkout-components/src/funding/venmo/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/venmo'>;
}
declare module '@paypal/checkout-components/src/funding/venmo/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/venmo'>;
}
declare module '@paypal/checkout-components/src/funding/venmo/template.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/venmo/template'>;
}
declare module '@paypal/checkout-components/src/funding/wechatpay/config.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/wechatpay/config'>;
}
declare module '@paypal/checkout-components/src/funding/wechatpay/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/wechatpay'>;
}
declare module '@paypal/checkout-components/src/funding/wechatpay/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/funding/wechatpay'>;
}
declare module '@paypal/checkout-components/src/hosted-buttons/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/hosted-buttons'>;
}
declare module '@paypal/checkout-components/src/hosted-buttons/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/hosted-buttons'>;
}
declare module '@paypal/checkout-components/src/hosted-buttons/index.test.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/hosted-buttons/index.test'>;
}
declare module '@paypal/checkout-components/src/hosted-buttons/types.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/hosted-buttons/types'>;
}
declare module '@paypal/checkout-components/src/hosted-buttons/utils.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/hosted-buttons/utils'>;
}
declare module '@paypal/checkout-components/src/hosted-buttons/utils.test.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/hosted-buttons/utils.test'>;
}
declare module '@paypal/checkout-components/src/interface/button.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/interface/button'>;
}
declare module '@paypal/checkout-components/src/interface/card-fields.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/interface/card-fields'>;
}
declare module '@paypal/checkout-components/src/interface/fields.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/interface/fields'>;
}
declare module '@paypal/checkout-components/src/interface/hosted-buttons.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/interface/hosted-buttons'>;
}
declare module '@paypal/checkout-components/src/interface/marks.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/interface/marks'>;
}
declare module '@paypal/checkout-components/src/interface/payment-fields.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/interface/payment-fields'>;
}
declare module '@paypal/checkout-components/src/interface/wallet.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/interface/wallet'>;
}
declare module '@paypal/checkout-components/src/lib/api.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/lib/api'>;
}
declare module '@paypal/checkout-components/src/lib/errors.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/lib/errors'>;
}
declare module '@paypal/checkout-components/src/lib/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/lib'>;
}
declare module '@paypal/checkout-components/src/lib/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/lib'>;
}
declare module '@paypal/checkout-components/src/lib/isRTLLanguage.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/lib/isRTLLanguage'>;
}
declare module '@paypal/checkout-components/src/lib/perceived-latency-instrumentation.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/lib/perceived-latency-instrumentation'>;
}
declare module '@paypal/checkout-components/src/lib/security.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/lib/security'>;
}
declare module '@paypal/checkout-components/src/lib/session.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/lib/session'>;
}
declare module '@paypal/checkout-components/src/marks/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/marks/component'>;
}
declare module '@paypal/checkout-components/src/marks/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/marks'>;
}
declare module '@paypal/checkout-components/src/marks/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/marks'>;
}
declare module '@paypal/checkout-components/src/marks/template.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/marks/template'>;
}
declare module '@paypal/checkout-components/src/shopper-insights/interface.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/shopper-insights/interface'>;
}
declare module '@paypal/checkout-components/src/shopper-insights/shopperSession.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/shopper-insights/shopperSession'>;
}
declare module '@paypal/checkout-components/src/shopper-insights/shopperSession.test.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/shopper-insights/shopperSession.test'>;
}
declare module '@paypal/checkout-components/src/types.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/types'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/button.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/button'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/buttons.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/buttons'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/config'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/content.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/content'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/menu-button/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/menu-button'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/menu-button/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/menu-button'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/menu-button/menu-button.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/menu-button/menu-button'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/message.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/message'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/poweredBy.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/poweredBy'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/props.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/props'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/script.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/script'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/spinner.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/spinner'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/style.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/style'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/styles/base.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/styles/base'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/styles/button.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/styles/button'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/styles/color.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/styles/color'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/styles/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/styles'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/styles/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/styles'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/styles/labels.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/styles/labels'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/styles/page.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/styles/page'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/styles/responsive.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/styles/responsive'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/tagline.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/tagline'>;
}
declare module '@paypal/checkout-components/src/ui/buttons/util.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/buttons/util'>;
}
declare module '@paypal/checkout-components/src/ui/chevron.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/chevron'>;
}
declare module '@paypal/checkout-components/src/ui/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui'>;
}
declare module '@paypal/checkout-components/src/ui/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui'>;
}
declare module '@paypal/checkout-components/src/ui/loading.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/loading'>;
}
declare module '@paypal/checkout-components/src/ui/text/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/text'>;
}
declare module '@paypal/checkout-components/src/ui/text/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/text'>;
}
declare module '@paypal/checkout-components/src/ui/text/text.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/text/text'>;
}
declare module '@paypal/checkout-components/src/ui/tracking.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/ui/tracking'>;
}
declare module '@paypal/checkout-components/src/zoid/buttons/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/buttons/component'>;
}
declare module '@paypal/checkout-components/src/zoid/buttons/container.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/buttons/container'>;
}
declare module '@paypal/checkout-components/src/zoid/buttons/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/buttons'>;
}
declare module '@paypal/checkout-components/src/zoid/buttons/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/buttons'>;
}
declare module '@paypal/checkout-components/src/zoid/buttons/prerender.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/buttons/prerender'>;
}
declare module '@paypal/checkout-components/src/zoid/buttons/util.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/buttons/util'>;
}
declare module '@paypal/checkout-components/src/zoid/card-fields/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/card-fields/component'>;
}
declare module '@paypal/checkout-components/src/zoid/card-fields/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/card-fields'>;
}
declare module '@paypal/checkout-components/src/zoid/card-fields/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/card-fields'>;
}
declare module '@paypal/checkout-components/src/zoid/card-fields/prerender.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/card-fields/prerender'>;
}
declare module '@paypal/checkout-components/src/zoid/card-form/component.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/card-form/component'>;
}
declare module '@paypal/checkout-components/src/zoid/card-form/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/card-form'>;
}
declare module '@paypal/checkout-components/src/zoid/card-form/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/card-form'>;
}
declare module '@paypal/checkout-components/src/zoid/checkout/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/checkout/component'>;
}
declare module '@paypal/checkout-components/src/zoid/checkout/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/checkout/config'>;
}
declare module '@paypal/checkout-components/src/zoid/checkout/hacks.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/checkout/hacks'>;
}
declare module '@paypal/checkout-components/src/zoid/checkout/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/checkout'>;
}
declare module '@paypal/checkout-components/src/zoid/checkout/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/checkout'>;
}
declare module '@paypal/checkout-components/src/zoid/checkout/props.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/checkout/props'>;
}
declare module '@paypal/checkout-components/src/zoid/content.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/content'>;
}
declare module '@paypal/checkout-components/src/zoid/installments/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/installments/component'>;
}
declare module '@paypal/checkout-components/src/zoid/installments/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/installments'>;
}
declare module '@paypal/checkout-components/src/zoid/installments/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/installments'>;
}
declare module '@paypal/checkout-components/src/zoid/installments/props.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/installments/props'>;
}
declare module '@paypal/checkout-components/src/zoid/menu/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/menu/component'>;
}
declare module '@paypal/checkout-components/src/zoid/menu/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/menu'>;
}
declare module '@paypal/checkout-components/src/zoid/menu/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/menu'>;
}
declare module '@paypal/checkout-components/src/zoid/menu/props.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/menu/props'>;
}
declare module '@paypal/checkout-components/src/zoid/modal/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/modal/component'>;
}
declare module '@paypal/checkout-components/src/zoid/modal/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/modal'>;
}
declare module '@paypal/checkout-components/src/zoid/modal/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/modal'>;
}
declare module '@paypal/checkout-components/src/zoid/modal/props.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/modal/props'>;
}
declare module '@paypal/checkout-components/src/zoid/payment-fields/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/payment-fields/component'>;
}
declare module '@paypal/checkout-components/src/zoid/payment-fields/container.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/payment-fields/container'>;
}
declare module '@paypal/checkout-components/src/zoid/payment-fields/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/payment-fields'>;
}
declare module '@paypal/checkout-components/src/zoid/payment-fields/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/payment-fields'>;
}
declare module '@paypal/checkout-components/src/zoid/payment-fields/prerender.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/payment-fields/prerender'>;
}
declare module '@paypal/checkout-components/src/zoid/payment-fields/props.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/payment-fields/props'>;
}
declare module '@paypal/checkout-components/src/zoid/qr-code/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/qr-code/component'>;
}
declare module '@paypal/checkout-components/src/zoid/qr-code/container.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/qr-code/container'>;
}
declare module '@paypal/checkout-components/src/zoid/qr-code/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/qr-code'>;
}
declare module '@paypal/checkout-components/src/zoid/qr-code/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/qr-code'>;
}
declare module '@paypal/checkout-components/src/zoid/qr-code/prerender.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/qr-code/prerender'>;
}
declare module '@paypal/checkout-components/src/zoid/qr-code/types.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/qr-code/types'>;
}
declare module '@paypal/checkout-components/src/zoid/venmo/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/venmo/component'>;
}
declare module '@paypal/checkout-components/src/zoid/venmo/config.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/venmo/config'>;
}
declare module '@paypal/checkout-components/src/zoid/venmo/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/venmo'>;
}
declare module '@paypal/checkout-components/src/zoid/venmo/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/venmo'>;
}
declare module '@paypal/checkout-components/src/zoid/wallet/component.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/wallet/component'>;
}
declare module '@paypal/checkout-components/src/zoid/wallet/container.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/wallet/container'>;
}
declare module '@paypal/checkout-components/src/zoid/wallet/index' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/wallet'>;
}
declare module '@paypal/checkout-components/src/zoid/wallet/index.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/wallet'>;
}
declare module '@paypal/checkout-components/src/zoid/wallet/prerender.jsx' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/wallet/prerender'>;
}
declare module '@paypal/checkout-components/src/zoid/wallet/props.js' {
  declare module.exports: $Exports<'@paypal/checkout-components/src/zoid/wallet/props'>;
}
