// flow-typed signature: bb951e60f00ff9d92192a9df591db8e0
// flow-typed version: <<STUB>>/@paypal/example-components_v1.0.28/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/example-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/example-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/example-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/example-components/src/babel.config' {
  declare module.exports: any;
}

declare module '@paypal/example-components/src/component' {
  declare module.exports: any;
}

declare module '@paypal/example-components/src/declarations' {
  declare module.exports: any;
}

declare module '@paypal/example-components/src' {
  declare module.exports: any;
}

declare module '@paypal/example-components/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/example-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/example-components/__sdk__'>;
}
declare module '@paypal/example-components/src/babel.config.js' {
  declare module.exports: $Exports<'@paypal/example-components/src/babel.config'>;
}
declare module '@paypal/example-components/src/component.js' {
  declare module.exports: $Exports<'@paypal/example-components/src/component'>;
}
declare module '@paypal/example-components/src/declarations.js' {
  declare module.exports: $Exports<'@paypal/example-components/src/declarations'>;
}
declare module '@paypal/example-components/src/index' {
  declare module.exports: $Exports<'@paypal/example-components/src'>;
}
declare module '@paypal/example-components/src/index.js' {
  declare module.exports: $Exports<'@paypal/example-components/src'>;
}
declare module '@paypal/example-components/src/types.js' {
  declare module.exports: $Exports<'@paypal/example-components/src/types'>;
}
