// flow-typed signature: 85bd4e9b16cc19ebd69c2b79dbba8e8e
// flow-typed version: <<STUB>>/@paypal/googlepay-components_v1.2.3/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/googlepay-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/googlepay-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/googlepay-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/globals' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/__tests__/googlepay.test' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/babel.config' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/component' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/constants' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/googlepay' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/logging' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/mock' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/types' {
  declare module.exports: any;
}

declare module '@paypal/googlepay-components/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/googlepay-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/__sdk__'>;
}
declare module '@paypal/googlepay-components/globals.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/globals'>;
}
declare module '@paypal/googlepay-components/src/__tests__/googlepay.test.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/__tests__/googlepay.test'>;
}
declare module '@paypal/googlepay-components/src/babel.config.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/babel.config'>;
}
declare module '@paypal/googlepay-components/src/component.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/component'>;
}
declare module '@paypal/googlepay-components/src/constants.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/constants'>;
}
declare module '@paypal/googlepay-components/src/googlepay.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/googlepay'>;
}
declare module '@paypal/googlepay-components/src/index' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src'>;
}
declare module '@paypal/googlepay-components/src/index.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src'>;
}
declare module '@paypal/googlepay-components/src/logging.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/logging'>;
}
declare module '@paypal/googlepay-components/src/mock.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/mock'>;
}
declare module '@paypal/googlepay-components/src/types.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/types'>;
}
declare module '@paypal/googlepay-components/src/util.js' {
  declare module.exports: $Exports<'@paypal/googlepay-components/src/util'>;
}
