// flow-typed signature: 65ab24ee64b00753ff72ef77cd0bfdf2
// flow-typed version: <<STUB>>/@paypal/identity-components_v5.0.14/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/identity-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/identity-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/identity-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/dist/button' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/globals' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/constants/button' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/constants/class' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/constants' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/constants/misc' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/declarations' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/interface/button' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/types' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/button' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/content' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/props' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/style' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/styles/base' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/styles/button' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/styles/color' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/styles' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/styles/labels' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/button/styles/page' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/ui/text' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/auth/component' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/auth/config' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/auth' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/auth/props' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/button/component' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/button/container' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/button' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/button/prerender' {
  declare module.exports: any;
}

declare module '@paypal/identity-components/src/zoid/button/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/identity-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/identity-components/__sdk__'>;
}
declare module '@paypal/identity-components/dist/button.js' {
  declare module.exports: $Exports<'@paypal/identity-components/dist/button'>;
}
declare module '@paypal/identity-components/globals.js' {
  declare module.exports: $Exports<'@paypal/identity-components/globals'>;
}
declare module '@paypal/identity-components/src/constants/button.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/constants/button'>;
}
declare module '@paypal/identity-components/src/constants/class.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/constants/class'>;
}
declare module '@paypal/identity-components/src/constants/index' {
  declare module.exports: $Exports<'@paypal/identity-components/src/constants'>;
}
declare module '@paypal/identity-components/src/constants/index.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/constants'>;
}
declare module '@paypal/identity-components/src/constants/misc.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/constants/misc'>;
}
declare module '@paypal/identity-components/src/declarations.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/declarations'>;
}
declare module '@paypal/identity-components/src/interface/button.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/interface/button'>;
}
declare module '@paypal/identity-components/src/types.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/types'>;
}
declare module '@paypal/identity-components/src/ui/button/button.jsx' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/button'>;
}
declare module '@paypal/identity-components/src/ui/button/content.jsx' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/content'>;
}
declare module '@paypal/identity-components/src/ui/button/index' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button'>;
}
declare module '@paypal/identity-components/src/ui/button/index.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button'>;
}
declare module '@paypal/identity-components/src/ui/button/props.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/props'>;
}
declare module '@paypal/identity-components/src/ui/button/style.jsx' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/style'>;
}
declare module '@paypal/identity-components/src/ui/button/styles/base.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/styles/base'>;
}
declare module '@paypal/identity-components/src/ui/button/styles/button.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/styles/button'>;
}
declare module '@paypal/identity-components/src/ui/button/styles/color.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/styles/color'>;
}
declare module '@paypal/identity-components/src/ui/button/styles/index' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/styles'>;
}
declare module '@paypal/identity-components/src/ui/button/styles/index.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/styles'>;
}
declare module '@paypal/identity-components/src/ui/button/styles/labels.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/styles/labels'>;
}
declare module '@paypal/identity-components/src/ui/button/styles/page.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/button/styles/page'>;
}
declare module '@paypal/identity-components/src/ui/index' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui'>;
}
declare module '@paypal/identity-components/src/ui/index.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui'>;
}
declare module '@paypal/identity-components/src/ui/text.jsx' {
  declare module.exports: $Exports<'@paypal/identity-components/src/ui/text'>;
}
declare module '@paypal/identity-components/src/zoid/auth/component.jsx' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/auth/component'>;
}
declare module '@paypal/identity-components/src/zoid/auth/config.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/auth/config'>;
}
declare module '@paypal/identity-components/src/zoid/auth/index' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/auth'>;
}
declare module '@paypal/identity-components/src/zoid/auth/index.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/auth'>;
}
declare module '@paypal/identity-components/src/zoid/auth/props.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/auth/props'>;
}
declare module '@paypal/identity-components/src/zoid/button/component.jsx' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/button/component'>;
}
declare module '@paypal/identity-components/src/zoid/button/container.jsx' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/button/container'>;
}
declare module '@paypal/identity-components/src/zoid/button/index' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/button'>;
}
declare module '@paypal/identity-components/src/zoid/button/index.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/button'>;
}
declare module '@paypal/identity-components/src/zoid/button/prerender.jsx' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/button/prerender'>;
}
declare module '@paypal/identity-components/src/zoid/button/util.js' {
  declare module.exports: $Exports<'@paypal/identity-components/src/zoid/button/util'>;
}
