// flow-typed signature: 0ea192fdbd1e3f1aebb75b08ea40d475
// flow-typed version: <<STUB>>/@paypal/legal-components_v1.2.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/legal-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/legal-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/legal-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/legal-components/dist' {
  declare module.exports: any;
}

declare module '@paypal/legal-components/src/babel.config' {
  declare module.exports: any;
}

declare module '@paypal/legal-components/src/component' {
  declare module.exports: any;
}

declare module '@paypal/legal-components/src/constants' {
  declare module.exports: any;
}

declare module '@paypal/legal-components/src' {
  declare module.exports: any;
}

declare module '@paypal/legal-components/src/types' {
  declare module.exports: any;
}

declare module '@paypal/legal-components/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/legal-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/legal-components/__sdk__'>;
}
declare module '@paypal/legal-components/dist/index' {
  declare module.exports: $Exports<'@paypal/legal-components/dist'>;
}
declare module '@paypal/legal-components/dist/index.js' {
  declare module.exports: $Exports<'@paypal/legal-components/dist'>;
}
declare module '@paypal/legal-components/src/babel.config.js' {
  declare module.exports: $Exports<'@paypal/legal-components/src/babel.config'>;
}
declare module '@paypal/legal-components/src/component.js' {
  declare module.exports: $Exports<'@paypal/legal-components/src/component'>;
}
declare module '@paypal/legal-components/src/constants.js' {
  declare module.exports: $Exports<'@paypal/legal-components/src/constants'>;
}
declare module '@paypal/legal-components/src/index' {
  declare module.exports: $Exports<'@paypal/legal-components/src'>;
}
declare module '@paypal/legal-components/src/index.js' {
  declare module.exports: $Exports<'@paypal/legal-components/src'>;
}
declare module '@paypal/legal-components/src/types.js' {
  declare module.exports: $Exports<'@paypal/legal-components/src/types'>;
}
declare module '@paypal/legal-components/src/util/index' {
  declare module.exports: $Exports<'@paypal/legal-components/src/util'>;
}
declare module '@paypal/legal-components/src/util/index.js' {
  declare module.exports: $Exports<'@paypal/legal-components/src/util'>;
}
