// flow-typed signature: adf45018297ff966695a9de88d66f248
// flow-typed version: <<STUB>>/@paypal/messaging-components_v1.64.1/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/messaging-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/messaging-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/messaging-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/messaging' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/renderMessage' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-message' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-US-EZP' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-v2-lander' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-v2' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/messaging@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/modal@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/renderMessage@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-message@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-US-EZP@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-v2-lander@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-v2@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/messaging' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/renderMessage' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-message' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-US-EZP' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-v2-lander' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-v2' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/messaging@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/modal@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/renderMessage@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-message@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-US-EZP@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-v2-lander@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-v2@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/messaging' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/renderMessage' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-message' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-US-EZP' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-v2-lander' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-v2' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/messaging@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/modal@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/renderMessage@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-message@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-US-EZP@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-v2-lander@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-v2@1.64.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/globals' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/controllers/message/adapter' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/controllers/message/destroy' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/controllers/message' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/controllers/message/interface' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/controllers/message/setup' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/controllers/modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/controllers/modal/interface' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/controllers/modal/setup' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/interface' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/messaging' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/message/component' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/message/containerTemplate' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/message' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/message/validation' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/modal/component' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/modal/containerTemplate' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/modal/prerenderTemplate' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/treatments/component' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/library/zoid/treatments' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/activeTags' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/adblock' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/constants' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/debug' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/elements' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/events' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/experiments' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/functional' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/global' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/logger' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/miscellaneous' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/objects' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/observers' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/performance' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/sdk' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/server' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/stats' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/messaging-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/__sdk__'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/messaging.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/messaging'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/modal.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/modal'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/renderMessage.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/renderMessage'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-message.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/smart-credit-message'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-US-EZP.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-US-EZP'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-v2-lander.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-v2-lander'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-v2.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal-v2'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/messaging@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/messaging@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/modal@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/modal@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/renderMessage@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/renderMessage@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-message@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-message@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-US-EZP@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-US-EZP@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-v2-lander@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-v2-lander@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-v2@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal-v2@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/messaging.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/messaging'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/modal.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/modal'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/renderMessage.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/renderMessage'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-message.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-message'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-US-EZP.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-US-EZP'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-v2-lander.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-v2-lander'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-v2.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/smart-credit-modal-v2'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/messaging@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/messaging@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/modal@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/modal@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/renderMessage@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/renderMessage@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-message@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-message@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-US-EZP@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-US-EZP@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-v2-lander@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-v2-lander@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-v2@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/sandbox/versioned/smart-credit-modal-v2@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/messaging.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/messaging'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/modal.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/modal'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/renderMessage.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/renderMessage'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-message.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-message'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-US-EZP.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-US-EZP'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-v2-lander.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-v2-lander'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-v2.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/smart-credit-modal-v2'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/messaging@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/versioned/messaging@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/modal@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/versioned/modal@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/renderMessage@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/versioned/renderMessage@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-message@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-message@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-US-EZP@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-US-EZP@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-v2-lander@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-v2-lander@1.64.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-v2@1.64.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/stage/versioned/smart-credit-modal-v2@1.64.1'>;
}
declare module '@paypal/messaging-components/globals.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/globals'>;
}
declare module '@paypal/messaging-components/src/library/controllers/message/adapter.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/message/adapter'>;
}
declare module '@paypal/messaging-components/src/library/controllers/message/destroy.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/message/destroy'>;
}
declare module '@paypal/messaging-components/src/library/controllers/message/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/message'>;
}
declare module '@paypal/messaging-components/src/library/controllers/message/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/message'>;
}
declare module '@paypal/messaging-components/src/library/controllers/message/interface.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/message/interface'>;
}
declare module '@paypal/messaging-components/src/library/controllers/message/setup.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/message/setup'>;
}
declare module '@paypal/messaging-components/src/library/controllers/modal/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/modal'>;
}
declare module '@paypal/messaging-components/src/library/controllers/modal/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/modal'>;
}
declare module '@paypal/messaging-components/src/library/controllers/modal/interface.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/modal/interface'>;
}
declare module '@paypal/messaging-components/src/library/controllers/modal/setup.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/controllers/modal/setup'>;
}
declare module '@paypal/messaging-components/src/library/interface/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/interface'>;
}
declare module '@paypal/messaging-components/src/library/interface/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/interface'>;
}
declare module '@paypal/messaging-components/src/library/messaging.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/messaging'>;
}
declare module '@paypal/messaging-components/src/library/modal.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/modal'>;
}
declare module '@paypal/messaging-components/src/library/zoid/message/component.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/message/component'>;
}
declare module '@paypal/messaging-components/src/library/zoid/message/containerTemplate.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/message/containerTemplate'>;
}
declare module '@paypal/messaging-components/src/library/zoid/message/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/message'>;
}
declare module '@paypal/messaging-components/src/library/zoid/message/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/message'>;
}
declare module '@paypal/messaging-components/src/library/zoid/message/validation.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/message/validation'>;
}
declare module '@paypal/messaging-components/src/library/zoid/modal/component.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/modal/component'>;
}
declare module '@paypal/messaging-components/src/library/zoid/modal/containerTemplate.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/modal/containerTemplate'>;
}
declare module '@paypal/messaging-components/src/library/zoid/modal/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/modal'>;
}
declare module '@paypal/messaging-components/src/library/zoid/modal/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/modal'>;
}
declare module '@paypal/messaging-components/src/library/zoid/modal/prerenderTemplate.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/modal/prerenderTemplate'>;
}
declare module '@paypal/messaging-components/src/library/zoid/treatments/component.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/treatments/component'>;
}
declare module '@paypal/messaging-components/src/library/zoid/treatments/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/treatments'>;
}
declare module '@paypal/messaging-components/src/library/zoid/treatments/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/library/zoid/treatments'>;
}
declare module '@paypal/messaging-components/src/utils/activeTags.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/activeTags'>;
}
declare module '@paypal/messaging-components/src/utils/adblock.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/adblock'>;
}
declare module '@paypal/messaging-components/src/utils/constants.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/constants'>;
}
declare module '@paypal/messaging-components/src/utils/debug.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/debug'>;
}
declare module '@paypal/messaging-components/src/utils/elements.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/elements'>;
}
declare module '@paypal/messaging-components/src/utils/events.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/events'>;
}
declare module '@paypal/messaging-components/src/utils/experiments.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/experiments'>;
}
declare module '@paypal/messaging-components/src/utils/functional.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/functional'>;
}
declare module '@paypal/messaging-components/src/utils/global.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/global'>;
}
declare module '@paypal/messaging-components/src/utils/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils'>;
}
declare module '@paypal/messaging-components/src/utils/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils'>;
}
declare module '@paypal/messaging-components/src/utils/logger.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/logger'>;
}
declare module '@paypal/messaging-components/src/utils/miscellaneous.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/miscellaneous'>;
}
declare module '@paypal/messaging-components/src/utils/objects.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/objects'>;
}
declare module '@paypal/messaging-components/src/utils/observers.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/observers'>;
}
declare module '@paypal/messaging-components/src/utils/performance.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/performance'>;
}
declare module '@paypal/messaging-components/src/utils/sdk.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/sdk'>;
}
declare module '@paypal/messaging-components/src/utils/server.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/server'>;
}
declare module '@paypal/messaging-components/src/utils/stats.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/stats'>;
}
