// flow-typed signature: 4d85d39746e393d5dcd7f54ad0692afd
// flow-typed version: <<STUB>>/@paypal/muse-components_v1.3.93/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/muse-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/muse-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/muse-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/globals' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/component' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/declarations' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/constants' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/cookie-utils' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/ddl/event-handlers' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/ddl/shopping-ddl' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/debug-console-logger' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/fpti' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/generate-id' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/get-device-info' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/get-property-id' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/iframe-tools/create-iframe' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/iframe-tools/identity-manager' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/iframe-tools/iframe-manager' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/jetlore' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/jetloreTracker' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/legacy-analytics/analytics-init' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/legacy-analytics/analytics-purchase' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/legacy-analytics' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/legacy-analytics/legacy-fpti' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/legacy-analytics/merchant-user-event' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/load-js' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/local-storage/cart' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/local-storage/container' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/local-storage/identity' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/local-storage' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/local-storage/local-storage-manager' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/local-storage/property-id' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/local-storage/user' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/logger' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/mobile-check' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/shopping-analytics' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/shopping-attributes' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/shopping-fpti/event-handlers' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/shopping-fpti/shopping-event-conversions' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/shopping-fpti/shopping-fpti' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/shopping-trackers' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/tag-parsers/capture-page-data' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/tag-parsers/jsonld-parser' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/tag-parsers/microdata-parser' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/tag-parsers/og-parser' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/user-configuration' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/utils' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/validation' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/validation/limit-cart-items' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/validation/utils' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/lib/validation/validate-custom-event' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/messaging-component' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/messaging' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/shopping-component' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/shopping' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/storeCash' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/tracker-component' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/tracker' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types/cart' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types/config' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types/container' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types/events' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types/fpti' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types/shopping-events' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types/user' {
  declare module.exports: any;
}

declare module '@paypal/muse-components/src/types/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/muse-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/muse-components/__sdk__'>;
}
declare module '@paypal/muse-components/globals.js' {
  declare module.exports: $Exports<'@paypal/muse-components/globals'>;
}
declare module '@paypal/muse-components/src/component.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/component'>;
}
declare module '@paypal/muse-components/src/declarations.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/declarations'>;
}
declare module '@paypal/muse-components/src/index' {
  declare module.exports: $Exports<'@paypal/muse-components/src'>;
}
declare module '@paypal/muse-components/src/index.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src'>;
}
declare module '@paypal/muse-components/src/lib/constants.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/constants'>;
}
declare module '@paypal/muse-components/src/lib/cookie-utils.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/cookie-utils'>;
}
declare module '@paypal/muse-components/src/lib/ddl/event-handlers.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/ddl/event-handlers'>;
}
declare module '@paypal/muse-components/src/lib/ddl/shopping-ddl.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/ddl/shopping-ddl'>;
}
declare module '@paypal/muse-components/src/lib/debug-console-logger.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/debug-console-logger'>;
}
declare module '@paypal/muse-components/src/lib/fpti.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/fpti'>;
}
declare module '@paypal/muse-components/src/lib/generate-id.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/generate-id'>;
}
declare module '@paypal/muse-components/src/lib/get-device-info.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/get-device-info'>;
}
declare module '@paypal/muse-components/src/lib/get-property-id.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/get-property-id'>;
}
declare module '@paypal/muse-components/src/lib/iframe-tools/create-iframe.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/iframe-tools/create-iframe'>;
}
declare module '@paypal/muse-components/src/lib/iframe-tools/identity-manager.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/iframe-tools/identity-manager'>;
}
declare module '@paypal/muse-components/src/lib/iframe-tools/iframe-manager.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/iframe-tools/iframe-manager'>;
}
declare module '@paypal/muse-components/src/lib/jetlore.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/jetlore'>;
}
declare module '@paypal/muse-components/src/lib/jetloreTracker.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/jetloreTracker'>;
}
declare module '@paypal/muse-components/src/lib/legacy-analytics/analytics-init.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/legacy-analytics/analytics-init'>;
}
declare module '@paypal/muse-components/src/lib/legacy-analytics/analytics-purchase.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/legacy-analytics/analytics-purchase'>;
}
declare module '@paypal/muse-components/src/lib/legacy-analytics/index' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/legacy-analytics'>;
}
declare module '@paypal/muse-components/src/lib/legacy-analytics/index.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/legacy-analytics'>;
}
declare module '@paypal/muse-components/src/lib/legacy-analytics/legacy-fpti.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/legacy-analytics/legacy-fpti'>;
}
declare module '@paypal/muse-components/src/lib/legacy-analytics/merchant-user-event.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/legacy-analytics/merchant-user-event'>;
}
declare module '@paypal/muse-components/src/lib/load-js.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/load-js'>;
}
declare module '@paypal/muse-components/src/lib/local-storage/cart.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/local-storage/cart'>;
}
declare module '@paypal/muse-components/src/lib/local-storage/container.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/local-storage/container'>;
}
declare module '@paypal/muse-components/src/lib/local-storage/identity.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/local-storage/identity'>;
}
declare module '@paypal/muse-components/src/lib/local-storage/index' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/local-storage'>;
}
declare module '@paypal/muse-components/src/lib/local-storage/index.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/local-storage'>;
}
declare module '@paypal/muse-components/src/lib/local-storage/local-storage-manager.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/local-storage/local-storage-manager'>;
}
declare module '@paypal/muse-components/src/lib/local-storage/property-id.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/local-storage/property-id'>;
}
declare module '@paypal/muse-components/src/lib/local-storage/user.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/local-storage/user'>;
}
declare module '@paypal/muse-components/src/lib/logger.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/logger'>;
}
declare module '@paypal/muse-components/src/lib/mobile-check.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/mobile-check'>;
}
declare module '@paypal/muse-components/src/lib/shopping-analytics.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/shopping-analytics'>;
}
declare module '@paypal/muse-components/src/lib/shopping-attributes.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/shopping-attributes'>;
}
declare module '@paypal/muse-components/src/lib/shopping-fpti/event-handlers.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/shopping-fpti/event-handlers'>;
}
declare module '@paypal/muse-components/src/lib/shopping-fpti/shopping-event-conversions.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/shopping-fpti/shopping-event-conversions'>;
}
declare module '@paypal/muse-components/src/lib/shopping-fpti/shopping-fpti.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/shopping-fpti/shopping-fpti'>;
}
declare module '@paypal/muse-components/src/lib/shopping-trackers.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/shopping-trackers'>;
}
declare module '@paypal/muse-components/src/lib/tag-parsers/capture-page-data.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/tag-parsers/capture-page-data'>;
}
declare module '@paypal/muse-components/src/lib/tag-parsers/jsonld-parser.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/tag-parsers/jsonld-parser'>;
}
declare module '@paypal/muse-components/src/lib/tag-parsers/microdata-parser.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/tag-parsers/microdata-parser'>;
}
declare module '@paypal/muse-components/src/lib/tag-parsers/og-parser.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/tag-parsers/og-parser'>;
}
declare module '@paypal/muse-components/src/lib/user-configuration.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/user-configuration'>;
}
declare module '@paypal/muse-components/src/lib/utils.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/utils'>;
}
declare module '@paypal/muse-components/src/lib/validation/index' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/validation'>;
}
declare module '@paypal/muse-components/src/lib/validation/index.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/validation'>;
}
declare module '@paypal/muse-components/src/lib/validation/limit-cart-items.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/validation/limit-cart-items'>;
}
declare module '@paypal/muse-components/src/lib/validation/utils.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/validation/utils'>;
}
declare module '@paypal/muse-components/src/lib/validation/validate-custom-event.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/lib/validation/validate-custom-event'>;
}
declare module '@paypal/muse-components/src/messaging-component.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/messaging-component'>;
}
declare module '@paypal/muse-components/src/messaging.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/messaging'>;
}
declare module '@paypal/muse-components/src/shopping-component.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/shopping-component'>;
}
declare module '@paypal/muse-components/src/shopping.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/shopping'>;
}
declare module '@paypal/muse-components/src/storeCash.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/storeCash'>;
}
declare module '@paypal/muse-components/src/tracker-component.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/tracker-component'>;
}
declare module '@paypal/muse-components/src/tracker.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/tracker'>;
}
declare module '@paypal/muse-components/src/types/cart.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types/cart'>;
}
declare module '@paypal/muse-components/src/types/config.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types/config'>;
}
declare module '@paypal/muse-components/src/types/container.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types/container'>;
}
declare module '@paypal/muse-components/src/types/events.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types/events'>;
}
declare module '@paypal/muse-components/src/types/fpti.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types/fpti'>;
}
declare module '@paypal/muse-components/src/types/index' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types'>;
}
declare module '@paypal/muse-components/src/types/index.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types'>;
}
declare module '@paypal/muse-components/src/types/shopping-events.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types/shopping-events'>;
}
declare module '@paypal/muse-components/src/types/user.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types/user'>;
}
declare module '@paypal/muse-components/src/types/util.js' {
  declare module.exports: $Exports<'@paypal/muse-components/src/types/util'>;
}
