// flow-typed signature: cb736bea967905ae70db546ea1205a73
// flow-typed version: <<STUB>>/@krakenjs/grabthar-release_v^3.0.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@krakenjs/grabthar-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@krakenjs/grabthar-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@krakenjs/grabthar-release/scripts/cdnify' {
  declare module.exports: any;
}

declare module '@krakenjs/grabthar-release/scripts/dependency-test' {
  declare module.exports: any;
}

declare module '@krakenjs/grabthar-release/scripts/grabthar-utils' {
  declare module.exports: any;
}

declare module '@krakenjs/grabthar-release/scripts/prune' {
  declare module.exports: any;
}

declare module '@krakenjs/grabthar-release/scripts/validate-flat' {
  declare module.exports: any;
}

// Filename aliases
declare module '@krakenjs/grabthar-release/scripts/cdnify.js' {
  declare module.exports: $Exports<'@krakenjs/grabthar-release/scripts/cdnify'>;
}
declare module '@krakenjs/grabthar-release/scripts/dependency-test.js' {
  declare module.exports: $Exports<'@krakenjs/grabthar-release/scripts/dependency-test'>;
}
declare module '@krakenjs/grabthar-release/scripts/grabthar-utils.js' {
  declare module.exports: $Exports<'@krakenjs/grabthar-release/scripts/grabthar-utils'>;
}
declare module '@krakenjs/grabthar-release/scripts/prune.js' {
  declare module.exports: $Exports<'@krakenjs/grabthar-release/scripts/prune'>;
}
declare module '@krakenjs/grabthar-release/scripts/validate-flat.js' {
  declare module.exports: $Exports<'@krakenjs/grabthar-release/scripts/validate-flat'>;
}
